# roles/kubernetes/tasks/main.yml
---
- name: Add Kubernetes apt key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present

- name: Update apt cache after adding Kubernetes repository
  ansible.builtin.apt:
    update_cache: true

- name: Install Kubernetes packages
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: true

- name: Hold Kubernetes packages at current version
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    mark_hold: true

- name: Initialize Kubernetes cluster
  command: kubeadm init
  when: inventory_hostname == groups['kube_master'][0]

- name: Set up kubeconfig for root
  command: "{{ item }}"
  with_items:
    - mkdir -p $HOME/.kube
    - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - chown $(id -u):$(id -g) $HOME/.kube/config
  when: inventory_hostname == groups['kube_master'][0]

- name: Apply Calico network plugin
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  when: inventory_hostname == groups['kube_master'][0]