# ansible/roles/deploy/tasks/main.yml
---
- name: Clone the repository
  git:
    repo: 'https://gitlab.infra.connectwork.fr/epitech/sample-app.git'
    dest: /home/maintainer/sample-app
    version: master

- name: Copy docker-compose.prod.yml to the server
  copy:
    src: roles/deploy/files/docker-compose.prod.yml
    dest: /home/maintainer/sample-app/docker-compose.prod.yml

- name: Copy nginx.conf to the server
  copy:
    src: roles/deploy/files/nginx.conf
    dest: /home/maintainer/sample-app/nginx.conf

- name: Build and run the Docker containers
  command: docker compose -f /home/maintainer/sample-app/docker-compose.prod.yml up -d --build