---
- name: Playbook pour créer un fichier hello
  hosts: all
  become: true
  tasks:
    - name: Installer Git
      apt:
        name: git
        state: present

    - name: Cloner le dépôt de l'application
      git:
        repo: 'https://gitlab.infra.connectwork.fr/epitech/sample-app.git'
        dest: /home/maintainer/sample-app
        version: main

