# ansible/roles/post_config/tasks/main.yml
---
- name: Execute artisan migrate
  command: docker exec sample-app-app-1 php artisan migrate --force

- name: Seed the database
  command: docker exec sample-app-app-1 php artisan db:seed --force
